version: '3.8'

services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy

  frontend-with-nginx:
    build: 
      context: frontend
      args:
        EXTERNAL_BACKEND_API_URL: ${EXTERNAL_BACKEND_API_URL}
    ports:
      - 80:80
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
