version: '3.8'

services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/drinks_db
    depends_on:
      - db

  # frontend-with-nginx:
  #   build: frontend
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drinks_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
